/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DictTag: typeof import('./../components/dict-tag/dict-tag.vue')['default']
    FileUpload: typeof import('./../components/file-upload/file-upload.vue')['default']
    UnitPicker: typeof import('./../components/system-select/unit-picker.vue')['default']
    UserPicker: typeof import('./../components/system-select/user-picker.vue')['default']
  }
}
