/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/bpm/index" |
  "/pages/contact/index" |
  "/pages/message/index" |
  "/pages/user/index" |
  "/pages/general/leaveApply/dataForm" |
  "/pages/general/leaveApply/index" |
  "/pages/general/news/index" |
  "/pages/general/sealdeclaration/index" |
  "/pages/general/sealdeclaration/SealDeclarationForm" |
  "/pages/index/settings/index" |
  "/pages/general/camp/receptionapply/index" |
  "/pages/general/camp/receptionapply/ReceptionApplyForm" |
  "/pages/general/camp/safety/index" |
  "/pages/general/meeting/subscribe/index" |
  "/pages/general/meeting/subscribe/SubscribeForm" |
  "/pages/pms/document/consortium/posted/dataForm" |
  "/pages/pms/document/consortium/posted/index" |
  "/pages/pms/document/consortium/received/dataForm" |
  "/pages/pms/document/consortium/received/index" |
  "/pages/pms/document/construction/posted/dataForm" |
  "/pages/pms/document/construction/posted/index" |
  "/pages/pms/document/construction/received/dataForm" |
  "/pages/pms/document/construction/received/index" |
  "/pages/pms/document/owner/posted/dataForm" |
  "/pages/pms/document/owner/posted/index" |
  "/pages/pms/document/owner/received/dataForm" |
  "/pages/pms/document/owner/received/index" |
  "/pages/pms/document/supervision/posted/dataForm" |
  "/pages/pms/document/supervision/posted/index" |
  "/pages/pms/document/supervision/received/dataForm" |
  "/pages/pms/document/supervision/received/index" |
  "/pages/pms/safety/safeInspection/inspection/dataForm" |
  "/pages/pms/safety/safeInspection/inspection/index" |
  "/pages/pms/safety/safeInspection/rectification/dataForm" |
  "/pages/pms/safety/safeInspection/rectification/index" |
  "/pages-core/auth/code-login" |
  "/pages-core/auth/forget-password" |
  "/pages-core/auth/login copy" |
  "/pages-core/auth/login" |
  "/pages-core/auth/register" |
  "/pages-core/error/404" |
  "/pages-core/error/pc-only" |
  "/pages-core/user/feedback/index" |
  "/pages-core/user/profile/index" |
  "/pages-core/user/security/index" |
  "/pages-core/user/settings/index" |
  "/pages-core/user/settings/agreement/index" |
  "/pages-core/user/settings/privacy/index" |
  "/pages-bpm/category/index" |
  "/pages-bpm/process-expression/index" |
  "/pages-bpm/process-listener/index" |
  "/pages-bpm/user-group/index" |
  "/pages-bpm/category/detail/index" |
  "/pages-bpm/category/form/index" |
  "/pages-bpm/oa/leave/index" |
  "/pages-bpm/process-expression/detail/index" |
  "/pages-bpm/process-expression/form/index" |
  "/pages-bpm/process-listener/detail/index" |
  "/pages-bpm/process-listener/form/index" |
  "/pages-bpm/processInstance/create/index" |
  "/pages-bpm/processInstance/detail/index" |
  "/pages-bpm/processInstance/manager/index" |
  "/pages-bpm/task/manager/index" |
  "/pages-bpm/user-group/detail/index" |
  "/pages-bpm/user-group/form/index" |
  "/pages-bpm/oa/leave/create/index" |
  "/pages-bpm/oa/leave/detail/index" |
  "/pages-bpm/processInstance/detail/audit/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/bpm/index" | "/pages/message/index" | "/pages/user/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
